import Head from "next/head";
import React from "react";
import Grid from "./Grid";

const title = "Create your reservation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AllHeader title={title}> */}
      <Grid />
    </div>
  );
}
